[package]
name = "cookbook"
version = "0.0.0"

[lib]
path = "fake_lib.rs"

[dependencies]
clap = "2"
pest = "2.1"
pest_derive = "2.1"
regex = "1"
walkdir = "2"

[raze]
genmode = "Remote"
workspace_path = "//third-party/cargo"
target = "x86_64-unknown-linux-gnu"

[raze.crates.syn.'1.0.8']
gen_buildrs = true

[raze.crates.proc-macro2.'1.0.6']
additional_flags = [
  "--cfg=use_proc_macro",
  "--cfg=u128",
  "--cfg=wrap_proc_macro"
]

