[package]
name = "cookbook"
version = "0.0.0"

[lib]
path = "fake_lib.rs"

[dependencies]
pest = "2"
pest_derive = "2"
clap = "2"

[raze]
genmode = "Remote"
workspace_path = "//third-party/cargo"
target = "x86_64-unknown-linux-gnu"

[raze.crates.syn.'0.15.29']
gen_buildrs = true

[raze.crates.proc-macro2.'0.4.27']
additional_flags = [
  "--cfg=use_proc_macro",
  "--cfg=u128",
  "--cfg=wrap_proc_macro"
]

