version: "2.1"
jobs:
  build_java:
    working_directory: ~/cookbook
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: 
          command: "bash gradlew check"
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: ~/cookbook/build/reports/allTestsXml
  build_ui:
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    steps:
      - checkout
      - run:
          working_directory: ~/project/punchcard-ui
          command: yarn
      - run: 
          working_directory: ~/project/punchcard-ui
          command: yarn test

workflows:
  version: 2
  full_build:
    jobs:
    - build_java
    - build_ui
