version: "2.1"
jobs:
  build:
    working_directory: ~/cookbook
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: 
          when: always
          command: "bash gradlew check"
      - run: 
          when: always
          working_directory: ~/cookbook/punchcard-ui
          command: "yarn && yarn test"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: ~/cookbook/build/reports/allTestsXml

