version: 2
jobs:
  build:
    working_directory: ~/cookbook
    docker:
      - image: openjdk:8u121
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: |
              bash gradlew check -Pkotlin.incremental=false --no-daemon --info
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: server/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: frontend/coverage

