version: 2
jobs:
  build:
    working_directory: ~/cookbook
    docker:
      - image: openjdk:8u121
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: |
              export GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
              bash gradlew check -Pkotlin.incremental=false --no-daemon --info
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: server/build/test-results
          destination: test-results
      - store_test_results:
          path: core/build/test-results
          destination: test-results

