version: "2.1"
jobs:
  build_primary:
    working_directory: ~/cookbook
    docker:
      - image: l.gcr.io/google/bazel:0.29.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-bazel-cache
      - run: cp .circleci/bazel.rc /etc/bazel.bazelrc
      - run: echo "1.0.$CIRCLE_BUILD_NUM" | tee version_file
      - run: bazel build //...
      - run: bazel test //...
      - run: |
          mkdir tests
          find -L bazel-testlogs -name 'test.xml' -printf '%h\n' | xargs -n1 -I{} cp -r {} tests
          mkdir artifacts
          find -L bazel-bin -name '*.deb' -print -exec cp {} artifacts \;
      - store_test_results:
          path: tests
      - persist_to_workspace:
          root: artifacts
          paths:
            - "*.deb"
      - save_cache:
          key: v2-bazel-cache
          paths:
            - "/home/circleci/bazel_cache"
  build_ui:
    docker:
      - image: circleci/node:11.15.0-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn prettier:check
      - run: yarn workspaces run build
      - run: yarn workspaces run test --coverage --reporters=default --reporters=jest-junit
      - run: node .circleci/move-test-out.js
      - store_test_results:
          path: tests
      - persist_to_workspace:
          root: .
          paths:
            - packages/punchcard-ui/build
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/gopunchcard.deb
      - run: tar -cvzf punchcard-ui.tgz /tmp/workspace/packages/punchcard-ui/build
      - store_artifacts:
          path: punchcard-ui.tgz

workflows:
  version: 2
  full_build:
    jobs:
    - build_primary
    - build_ui
    - deploy:
        requires: [build_primary, build_ui]
        filters:
          branches:
            only: master
