version: "2.1"
jobs:
  build_primary:
    working_directory: ~/cookbook
    docker:
      - image: l.gcr.io/google/bazel:0.29.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bazel-cache-{{ checksum "WORKSPACE" }}
            - v1-bazel-cache
      - run: cp .circleci/bazel.rc /etc/bazel.bazelrc
      - run: echo "1.0.$CIRCLE_BUILD_NUM" | tee version_file
      - run: bazel build //...
      - run: bazel test //...
      - run: |
          mkdir tests
          find -L bazel-testlogs -name 'test.xml' -printf '%h\n' | xargs -n1 -I{} cp -r {} tests
          mkdir artifacts
          find -L bazel-bin -name '*.deb' -print -exec cp {} artifacts \;
      - store_test_results:
          path: tests
      - persist_to_workspace:
          paths:
            - "artifacts/*.deb"
      - store_artifacts:
          path: artifacts/punchcard.deb
      - store_artifacts:
          path: artifacts/gopunchcard.deb
      - save_cache:
          key: v1-bazel-cache-{{ checksum "WORKSPACE" }}
          paths:
            - "/home/circleci/.cache/bazel"
  build_ui:
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn workspaces run build
      - run: yarn workspaces run test
  deploy:
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/artifacts/punchcard.deb
      - store_artifacts:
          path: /tmp/workspace/artifacts/gopunchcard.deb

workflows:
  version: 2
  full_build:
    jobs:
    - build_primary
    - build_ui
    - deploy:
        requires: [build_primary]
        filters:
          branches:
            only: master
