version: 2
jobs:
  build:
    working_directory: ~/cookbook
    docker:
      - image: openjdk:8u121
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}
      - run: |
              bash gradlew assemble -Pkotlin.incremental=false --no-daemon
              bash gradlew check -Pkotlin.incremental=false --no-daemon
      - save_cache:
          paths:
            - ~/.m2
          key: v1-{{ checksum "build.gradle" }}
      - store_test_results:
          path: server/build/test-results
          destination: test-results

