version: "2.1"
jobs:
  build_primary:
    working_directory: ~/cookbook
    docker:
      - image: l.gcr.io/google/bazel:0.29.0
    steps:
      - checkout
      - restore_cache:
          key: "v1-bazel-cache"
      - run: cp .circleci/bazel.rc /etc/bazel.bazelrc
      - run: bazel build //...
      - run: bazel test //...
      - run: |
          mkdir tmp
          find -L bazel-testlogs -name 'test.xml' -printf '%h\n' | xargs -n1 -I{} cp -r {} tmp
      - store_test_results:
          path: tmp
      - save_cache:
          key: "v1-bazel-cache"
          paths:
            - "/home/circleci/.cache/bazel"
  build_ui:
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn workspaces run build
      - run: yarn workspaces run test

workflows:
  version: 2
  full_build:
    jobs:
    - build_primary
    - build_ui
